const employTypes = {
  INITIAL_SATE: 'EMPLOYEE_INITIAL_SATE',
  NEW: 'EMPLOYEE_NEW',
  CREATING: 'EMPLOYEE_CREATING',
  CREATED_SUCESS: 'EMPLOYEE_CREATED_SUCESS',
  EMPLOYEE_PROP_CHANGE: 'EMPLOYEE_PROP_CHANGE'
};

export default employTypes;