const employTypes = {
  INITIAL_SATE: 'EMPLOYEE_INITIAL_SATE',

  NEW: 'EMPLOYEE_NEW',

  CREATE: 'EMPLOYEE_CREATE',
  CREATE_SUCESS: 'EMPLOYEE_CREATE_SUCESS',
  CREATE_ERROR: 'EMPLOYEE_CREATE_ERROR',

  PROP_CHANGE: 'EMPLOYEE_PROP_CHANGE'
};

export default employTypes;