const employTypes = {
  INITIAL_SATE: 'EMPLOYE_INITIAL_SATE',

  NEW: 'EMPLOYE_NEW',

  CREATE: 'EMPLOYE_CREATE',
  CREATE_SUCESS: 'EMPLOYE_CREATE_SUCESS',
  CREATE_ERROR: 'EMPLOYE_CREATE_ERROR',

  PROP_CHANGE: 'EMPLOYE_PROP_CHANGE',

  FETCH: 'EMPLOYE_FETCH',
  FETCH_SUCESS: 'EMPLOYE_FETCH_SUCESS',
  FETCH_ERROR: 'EMPLOYE_FETCH_ERROR',
};

export default employTypes;