const authTypes = {
  INITIAL_SATE: 'AUTH_INITIAL_SATE',

  SIGN_IN: 'AUTH_SIGN_IN',
  SIGN_IN_SUCESS: 'AUTH_SIGN_IN_SUCESS',
  SIGN_IN_ERROR: 'AUTH_SIGN_IN_ERROR',

  SIGN_OUT: 'AUTH_SIGN_OUT',
  SIGN_OUT_SUCESS: 'AUTH_SIGN_OUT_SUCESS',
  SIGN_OUT_ERROR: 'AUTH_SIGN_OUT_ERROR',

  AUTO_SIGN_IN: 'AUTH_AUTO_SIGN_IN',
  AUTO_SIGN_IN_SUCESS: 'AUTH_AUTO_SIGN_IN_SUCESS',
  AUTO_SIGN_IN_FAIL: 'AUTH_AUTO_SIGN_IN_FAIL',

  CREATE_USER: 'AUTH_CREATED_USER',
  CREATE_USER_SUCESS: 'AUTH_CREATE_USER_SUCESS',
  CREATE_USER_ERROR: 'AUTH_CREATE_USER_ERROR',

  PROP_CHANGE: 'AUTH_PROP_CHANGE'
};

export default authTypes;